# ----------------------------
# Makefile Options
# ----------------------------

NAME = BRKOUTB
ICON = icon.png
DESCRIPTION = "Atari 2600 Breakout on TI84+ CE (Version B)"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
