# ----------------------------
# Makefile Options
# ----------------------------

NAME = CONWAY
ICON = icon.png
DESCRIPTION = "Conways game of life running on the whole screen"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
