# ----------------------------
# Makefile Options
# ----------------------------

NAME = BRKOUTA
ICON = icon.png
DESCRIPTION = "Atari Breakout on TI84+ CE (Version A)"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
